# Generated by Django 2.1 on 2019-03-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190304_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hshows', to='webapp.Hall', verbose_name='Hall'),
        ),
    ]
