# Generated by Django 2.1 on 2019-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190304_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='movies', to='webapp.Category', verbose_name='Category'),
        ),
    ]
